source(here::here("scripts", "01_download_census.R"))
source(here::here("scripts", "02_prepare_gtfs.R"))
source(here::here("scripts", "03_prepare_walking_network.R"))
source(here::here("scripts", "04_prepare_destinations.R"))
source(here::here("scripts", "05_compute_accessibility.R"))
source(here::here("scripts", "06_summarize_metrics.R"))
source(here::here("scripts", "07_make_maps.R"))
source(here::here("scripts", "08_make_plots.R"))
